stages:
  - linting
  - testing

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose --config setup.cfg .

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --config pyproject.toml .

test:
  stage: testing
  image: python:3.10
  script:
    - pip install -r requirements/prod.txt
    - pip install -r requirements/test.txt
    - cd lyceum
    - python manage.py test