# Generated by Django 4.2.6 on 2023-12-15 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUserStatistics',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'include_tasks',
                    models.BooleanField(
                        help_text='Does statistics include tasks?',
                        verbose_name='include tasks',
                    ),
                ),
                (
                    'statistics_file',
                    models.FilePathField(
                        help_text='Path to file with user statistics',
                        verbose_name='user statistics file',
                    ),
                ),
                (
                    'date_from',
                    models.DateField(
                        help_text='Start date user statistics',
                        verbose_name='statistics from: (date)',
                    ),
                ),
                (
                    'date_to',
                    models.DateField(
                        help_text='End date user statistics',
                        verbose_name='statistics to: (date)',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Date of creation user statistics report',
                        verbose_name='date of creation',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
        ),
    ]
