# Generated by Django 4.2.6 on 2023-12-03 17:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(
                default='users/default_profile_image.png',
                upload_to=users.models.get_user_media_path,
                verbose_name='profile image',
            ),
        ),
    ]
