# Generated by Django 4.2.6 on 2023-12-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='expire_datetime',
        ),
        migrations.AddField(
            model_name='invite',
            name='expire_date',
            field=models.DateField(
                default=None, null=True, verbose_name='expire_date'
            ),
        ),
    ]
