# Generated by Django 4.2.6 on 2023-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_remove_invite_expire_datetime_invite_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invited_user',
        ),
        migrations.AddField(
            model_name='invite',
            name='invited_user_email',
            field=models.EmailField(
                default=None, max_length=254, verbose_name='invited_user_email'
            ),
            preserve_default=False,
        ),
    ]
