# Generated by Django 4.2.6 on 2023-11-30 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name for company',
                        max_length=150,
                        verbose_name='name',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Description for company',
                        verbose_name='description',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('owner', 'Owner'),
                            ('manager', 'Manager'),
                            ('employee', 'Employee'),
                        ],
                        help_text='Role for company user',
                        max_length=20,
                        verbose_name='role',
                    ),
                ),
                (
                    'score',
                    models.PositiveIntegerField(
                        help_text='User score count', verbose_name='score'
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='workplace.company',
                        verbose_name='company',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
        ),
    ]
