# Generated by Django 4.2.6 on 2023-11-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='Description for company',
                verbose_name='description',
            ),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='score',
            field=models.PositiveIntegerField(
                default=0, help_text='User score count', verbose_name='score'
            ),
        ),
    ]
