# Generated by Django 4.2.6 on 2023-12-11 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            'workplace',
            '0002_alter_company_description_alter_companyuser_score',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Task name',
                        max_length=300,
                        verbose_name='name',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='concrete task description',
                        verbose_name='task description',
                    ),
                ),
                ('deadline', models.DateTimeField(help_text='task deadline')),
                (
                    'manager',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='tasks_given',
                        to='workplace.companyuser',
                        verbose_name='created by manager',
                    ),
                ),
                (
                    'responsible',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='tasks',
                        to='workplace.companyuser',
                        verbose_name='responsible',
                    ),
                ),
            ],
        ),
    ]
