# Generated by Django 4.2.6 on 2023-12-17 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0004_rename_manager_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='end_time',
            field=models.TimeField(
                default=datetime.time(18, 0),
                help_text='time of ending of working day',
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='start_time',
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text='time of beginning of working day',
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='working_days',
            field=models.CharField(default='1111100', max_length=7),
        ),
    ]
