# Generated by Django 4.2.6 on 2023-12-15 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0004_rename_manager_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text='date of creation task',
                verbose_name='create date',
            ),
            preserve_default=False,
        ),
    ]
