# Generated by Django 4.2.6 on 2023-12-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0005_company_end_time_company_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(
                choices=[
                    ('owner', 'Owner'),
                    ('manager', 'Manager'),
                    ('employee', 'Employee'),
                ],
                default='owner',
                help_text='Task current state',
                max_length=20,
                verbose_name='state',
            ),
        ),
    ]
