# Generated by Django 4.2.6 on 2023-12-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0006_task_status_taskstatuschangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Date of task complition',
                null=True,
                verbose_name='complete date',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Date of creation task',
                verbose_name='create date',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(help_text='Task deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='Concrete task description',
                verbose_name='task description',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('in_processing', 'In Process'),
                    ('completed', 'Complete'),
                    ('on_checking', 'On Checking'),
                    ('rejected', 'Rejected'),
                ],
                default='in_processing',
                help_text='Current task status',
                max_length=20,
                verbose_name='task status',
            ),
        ),
        migrations.AlterField(
            model_name='taskstatuschangelog',
            name='from_status',
            field=models.CharField(
                choices=[
                    ('in_processing', 'In Process'),
                    ('completed', 'Complete'),
                    ('on_checking', 'On Checking'),
                    ('rejected', 'Rejected'),
                ],
                help_text='changed from: (task status)',
                max_length=20,
                verbose_name='from status',
            ),
        ),
        migrations.AlterField(
            model_name='taskstatuschangelog',
            name='to_status',
            field=models.CharField(
                choices=[
                    ('in_processing', 'In Process'),
                    ('completed', 'Complete'),
                    ('on_checking', 'On Checking'),
                    ('rejected', 'Rejected'),
                ],
                help_text='changed to: (task status)',
                max_length=20,
                verbose_name='to status',
            ),
        ),
    ]
