# Generated by Django 4.2.6 on 2023-12-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0006_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(
                choices=[
                    ('given', 'Given'),
                    ('active', 'Active'),
                    ('postponed', 'Postponed'),
                    ('review', 'On review'),
                    ('rejected', 'Rejected'),
                    ('completed', 'Completed'),
                ],
                default='given',
                help_text='Task current state',
                max_length=20,
                verbose_name='state',
            ),
        ),
    ]
