# Generated by Django 4.2.6 on 2023-12-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0007_task_completed_at_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('in_processing', 'In Processing'),
                    ('completed', 'Completed'),
                    ('on_checking', 'On Checking'),
                    ('rejected', 'Rejected'),
                ],
                default='in_processing',
                help_text='Current task status',
                max_length=20,
                verbose_name='task status',
            ),
        ),
        migrations.AlterField(
            model_name='taskstatuschangelog',
            name='from_status',
            field=models.CharField(
                choices=[
                    ('in_processing', 'In Processing'),
                    ('completed', 'Completed'),
                    ('on_checking', 'On Checking'),
                    ('rejected', 'Rejected'),
                ],
                help_text='changed from: (task status)',
                max_length=20,
                verbose_name='from status',
            ),
        ),
        migrations.AlterField(
            model_name='taskstatuschangelog',
            name='to_status',
            field=models.CharField(
                choices=[
                    ('in_processing', 'In Processing'),
                    ('completed', 'Completed'),
                    ('on_checking', 'On Checking'),
                    ('rejected', 'Rejected'),
                ],
                help_text='changed to: (task status)',
                max_length=20,
                verbose_name='to status',
            ),
        ),
    ]
