# Generated by Django 4.2.6 on 2023-12-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0007_alter_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_responsible',
            field=models.ForeignKey(
                help_text='leave blank if no review specified',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='review_tasks',
                to='workplace.companyuser',
                verbose_name='responsible for review',
            ),
        ),
    ]
