# Generated by Django 4.2.6 on 2023-12-21 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0005_company_end_time_company_start_time_and_more'),
        ('workplace', '0010_alter_companyuser_company_alter_companyuser_user'),
    ]

    operations = []
