# Generated by Django 4.2.6 on 2023-12-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0011_merge_20231221_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('given', 'Given'),
                    ('active', 'Active'),
                    ('postponed', 'Postponed'),
                    ('review', 'On review'),
                    ('rejected', 'Rejected'),
                    ('completed', 'Completed'),
                ],
                default='given',
                help_text='Task current status',
                max_length=20,
                verbose_name='status',
            ),
        ),
        migrations.AlterField(
            model_name='taskstatuschangelog',
            name='from_status',
            field=models.CharField(
                choices=[
                    ('given', 'Given'),
                    ('active', 'Active'),
                    ('postponed', 'Postponed'),
                    ('review', 'On review'),
                    ('rejected', 'Rejected'),
                    ('completed', 'Completed'),
                ],
                help_text='changed from: (task status)',
                max_length=20,
                verbose_name='from status',
            ),
        ),
        migrations.AlterField(
            model_name='taskstatuschangelog',
            name='to_status',
            field=models.CharField(
                choices=[
                    ('given', 'Given'),
                    ('active', 'Active'),
                    ('postponed', 'Postponed'),
                    ('review', 'On review'),
                    ('rejected', 'Rejected'),
                    ('completed', 'Completed'),
                ],
                help_text='changed to: (task status)',
                max_length=20,
                verbose_name='to status',
            ),
        ),
    ]
