# Generated by Django 4.2.6 on 2023-12-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('workplace', '0012_alter_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('message', models.TextField(verbose_name='review_message')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
        migrations.AddField(
            model_name='task',
            name='review_responsible',
            field=models.ForeignKey(
                help_text='leave blank if no review specified',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='review_tasks',
                to='workplace.companyuser',
                verbose_name='responsible for review',
            ),
        ),
        migrations.DeleteModel(
            name='TaskStatusChangeLog',
        ),
        migrations.AddField(
            model_name='review',
            name='task',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='review',
                to='workplace.task',
                verbose_name='task',
            ),
        ),
    ]
