# Generated by Django 4.2.6 on 2023-12-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            'workplace',
            '0013_review_alter_task_options_task_review_responsible_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='users',
                to='workplace.company',
                verbose_name='company',
            ),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='company_users',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='task',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name='review',
                to='workplace.task',
                verbose_name='task',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='review_responsible',
            field=models.ForeignKey(
                blank=True,
                help_text='leave blank if no review specified',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='review_tasks',
                to='workplace.companyuser',
                verbose_name='responsible for review',
            ),
        ),
    ]
